/**
 * GET /api/ai/video-status?op=<operation_name>
 *
 * Polls the Vertex AI Long-Running Operation status for a video
 * generated by /api/ai/video-invitation (Google Veo 2).
 *
 * Status lifecycle:
 *   processing → done (with outputUri) | failed (with error)
 *
 * Once done, outputUri is the gs:// path where the video is stored.
 * Caller should move/copy to a public CDN or Cloud Storage signed URL
 * and write to /ai_insights collection with insight_type: "video_invitation".
 *
 * Query Params:
 *   op (required) — the operation name returned by /api/ai/video-invitation
 *
 * Output:
 *   { status: "processing" } — still running
 *   { status: "done", output_uri, video_type, generation_seconds } — complete
 *   { status: "failed", error } — generation failed
 */

import { NextResponse } from "next/server";
import { pollOperation } from "@/lib/google-ai-client";

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const operationName = searchParams.get("op");

  if (!operationName || operationName.trim() === "") {
    return NextResponse.json(
      { error: "Missing required query parameter: op (operation name)" },
      { status: 400 }
    );
  }

  // Basic sanity check — Vertex AI operation names look like:
  // projects/{project}/locations/{location}/operations/{id}
  if (!operationName.startsWith("projects/")) {
    return NextResponse.json(
      { error: "Invalid operation name format. Expected: projects/{project}/locations/{location}/operations/{id}" },
      { status: 400 }
    );
  }

  try {
    const opStatus = await pollOperation(operationName);

    if (!opStatus.done) {
      return NextResponse.json({
        success: true,
        status: "processing",
        operation_name: operationName,
        metadata: opStatus.metadata ?? null,
      });
    }

    if (opStatus.error) {
      return NextResponse.json({
        success: false,
        status: "failed",
        operation_name: operationName,
        error: opStatus.error.message || "Unknown Veo generation error",
        error_code: opStatus.error.code ?? null,
      });
    }

    // Extract the GCS output URI from the response
    const responseObj = opStatus.response ?? {};
    // Veo 2 response shape: { videos: [{ gcsUri, mimeType }] }
    const videos = responseObj.videos ?? responseObj.generatedVideos ?? [];
    const firstVideo = Array.isArray(videos) && videos.length > 0 ? videos[0] : null;

    const outputUri =
      firstVideo?.gcsUri ||
      firstVideo?.resourceName ||
      responseObj.outputUri ||
      responseObj.gcsUri ||
      null;

    return NextResponse.json({
      success: true,
      status: "done",
      operation_name: operationName,
      output_uri: outputUri,
      mime_type: firstVideo?.mimeType ?? "video/mp4",
      video_count: videos.length,
      raw_response: responseObj,
      // Caller should:
      // 1. Generate a signed URL from output_uri (gs:// path)
      // 2. Write to /ai_insights: { insight_type: "video_invitation", result: { output_uri, signed_url, ... } }
    });
  } catch (err) {
    console.error("[video-status] Poll error:", err);
    return NextResponse.json(
      {
        success: false,
        status: "error",
        error: err.message,
      },
      { status: 500 }
    );
  }
}
